{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "5b48def8-9074-4003-bd43-651c8a1e179f",
   "metadata": {},
   "outputs": [],
   "source": [
    "from bs4 import BeautifulSoup\n",
    "import requests\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import csv"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "9e92fac5-de5f-4a74-a94a-d53ed98333cf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Scraping data from page 1\n",
      "Failed to retrieve the page. Status code: 503\n",
      "Scraping data from page 2\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1Best sellerin Laptop Backpacks \n",
      "Product Name: TRUE HUMAN EMPEROR® Anti-Theft backpack With USB charging Port Laptop bag/Office bag/college bag/travel bag with anti -theft back pocket (LEGEND)\n",
      "Product Price: 1,799\n",
      "Rating: 3.7 out of 5 stars\n",
      "Number of Reviews: 2,764\n",
      "\n",
      "\n",
      "Scraping data from page 3\n",
      "Failed to retrieve the page. Status code: 503\n",
      "Scraping data from page 4\n",
      "Failed to retrieve the page. Status code: 503\n",
      "Scraping data from page 5\n",
      "Failed to retrieve the page. Status code: 503\n",
      "Scraping data from page 6\n",
      "Failed to retrieve the page. Status code: 503\n",
      "Scraping data from page 7\n",
      "Failed to retrieve the page. Status code: 503\n",
      "Scraping data from page 8\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_15,206 \n",
      "Product Name: HAMMONDS FLYCATCHER Genuine Leather Laptop Bag for Men - Office Bag, Brown Color - Fits Up to 14/15.6/16 Inch Laptop/MacBook - Laptop Messenger Bags/Leather Bag for Men with Adjustable Shoulder Strap\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 5,206\n",
      "\n",
      "\n",
      "Scraping data from page 9\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_14 \n",
      "Product Name: Impulse IMP linear 45L Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Travel Backpack Water Resistant Fits Up to 16 Inch Laptop with 1 Year Warranty\n",
      "Product Price: 1,799\n",
      "Rating: 5.0 out of 5 stars\n",
      "Number of Reviews: 4\n",
      "\n",
      "\n",
      "Scraping data from page 10\n",
      "Failed to retrieve the page. Status code: 503\n",
      "Scraping data from page 11\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Product URL: https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_11,095 \n",
      "Product Name: Wildcraft 45 Ltrs Black Rucksack (8903338073840) (Extra Large Size)\n",
      "Product Price: 1,799\n",
      "Rating: 4.3 out of 5 stars\n",
      "Number of Reviews: 1,095\n",
      "\n",
      "\n",
      "Scraping data from page 12\n",
      "Failed to retrieve the page. Status code: 503\n",
      "Scraping data from page 13\n",
      "Failed to retrieve the page. Status code: 503\n",
      "Scraping data from page 14\n",
      "Failed to retrieve the page. Status code: 503\n",
      "Scraping data from page 15\n",
      "Failed to retrieve the page. Status code: 503\n",
      "Scraping data from page 16\n",
      "Failed to retrieve the page. Status code: 503\n",
      "Scraping data from page 17\n",
      "Failed to retrieve the page. Status code: 503\n",
      "Scraping data from page 18\n",
      "Failed to retrieve the page. Status code: 503\n",
      "Scraping data from page 19\n",
      "Failed to retrieve the page. Status code: 503\n",
      "Scraping data from page 20\n",
      "Failed to retrieve the page. Status code: 503\n"
     ]
    }
   ],
   "source": [
    "def get_product_data(page_url):\n",
    "    headers = {\n",
    "        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36',\n",
    "    }\n",
    "    response = requests.get(page_url, headers=headers)\n",
    "    \n",
    "    if response.status_code == 200:\n",
    "        soup = BeautifulSoup(response.text, 'html.parser')\n",
    "        \n",
    "        product_list = soup.find_all('div', {'data-asin': True})\n",
    "        \n",
    "        for product in product_list:\n",
    "            product_url = 'https://www.amazon.in/s?k=bags&crid=2M096C61O4MLT&qid=1653308124&sprefix=ba%2Caps%2C283&ref=sr_pg_1' + soup.find('a',attrs= {'class': 'a-link-normal s-underline-text s-underline-link-text s-link-style'}).text\n",
    "            product_name = soup.find('span', attrs= {'class': 'a-size-medium a-color-base a-text-normal'}).text\n",
    "            product_price = soup.find('span',attrs= {'class': 'a-price-whole'}).text\n",
    "            rating = soup.find('span',attrs= {'class': 'a-icon-alt'})\n",
    "            rating = rating.text if rating else 'N/A'\n",
    "            num_reviews = soup.find('span',attrs= {'class': 'a-size-base s-underline-text'})\n",
    "            num_reviews = num_reviews.text if num_reviews else 'N/A'\n",
    "            with open('amazon_products.csv', 'a', newline='', encoding='utf-8') as csvfile:\n",
    "                csv_writer = csv.writer(csvfile)\n",
    "                csv_writer.writerow([product_url, product_name, product_price, rating, num_reviews])\n",
    "\n",
    "            \n",
    "            print(\"Product URL:\", product_url)\n",
    "            print(\"Product Name:\", product_name)\n",
    "            print(\"Product Price:\", product_price)\n",
    "            print(\"Rating:\", rating)\n",
    "            print(\"Number of Reviews:\", num_reviews)\n",
    "            print(\"\\n\")\n",
    "    else:\n",
    "        print(\"Failed to retrieve the page. Status code:\", response.status_code)\n",
    "with open('amazon_products.csv', 'w', newline='', encoding='utf-8') as csvfile:\n",
    "    csv_writer = csv.writer(csvfile)\n",
    "    # Write header row\n",
    "    csv_writer.writerow([\"Product URL\", \"Product Name\", \"Product Price\", \"Rating\", \"Number of Reviews\"])\n",
    "        \n",
    "for page_number in range(1, 21):\n",
    "    page_url = f'https://www.amazon.in/s?k=bags&page={page_number}'\n",
    "    print(f\"Scraping data from page {page_number}\")\n",
    "    get_product_data(page_url)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e9cc29cf-0d6d-4c87-aa4c-7caf50966c36",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
